# Generated by Django 4.2 on 2023-04-25 10:15

import _socket
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.custom_fields
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.sites.managers
import edc_base.utils
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectScreening',
            fields=[
                ('slug', models.CharField(db_index=True, default='', editable=False, help_text='a field used for quick search', max_length=250, null=True)),
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('subject_identifier', models.CharField(max_length=50, verbose_name='Subject Identifier')),
                ('screening_identifier', models.CharField(max_length=36, unique=True, verbose_name='Screening Identifier')),
                ('report_datetime', models.DateTimeField(default=edc_base.utils.get_utcnow, help_text='Date and time of the report', verbose_name='Report Date and Time')),
                ('enrollment_interest', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Does the patient want to be enrolledinto the study?')),
                ('disinterest_reason', models.CharField(blank=True, choices=[('dont_want_to_participate', "I don't want to be part of a study"), ('dont_think_I_have_condition', "I don't think I have the condition"), ('partner_doesnt_want_to_participate', "My partner doesn't want me to participate"), ('OTHER', 'Other (specify)')], max_length=50, null=True, verbose_name='If no, reason patient does not wish to enrollinto the study')),
                ('disinterest_reason_other', edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...')),
                ('nationality', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=3, verbose_name='Is the potential paticipant a Botswana Citizen?')),
                ('married_to_motswana', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=3, verbose_name='If no,Is participant married to a Motswana')),
                ('proof_of_marriage', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', help_text="( if 'NO' STOP patient cannot be enrolled )", max_length=3, verbose_name='If yes,Can the participate show proof of marriage')),
                ('age_in_years', models.IntegerField(help_text='(Years)', verbose_name='Paticipants age')),
                ('literate', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Is the participant literate')),
                ('literate_witness', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=3, verbose_name='If no,Does participant have a literate witness')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined')], max_length=6, verbose_name='Are you male or female?')),
                ('enrollment_site', models.CharField(choices=[('mmathethe_clinic', 'Mmathethe clinic'), ('molapowabojang_clinic', 'Molapowabojang clinic'), ('otse_clinic', 'Otse clinic'), ('mmankgodi_clinic', 'Mmankgodi clinic'), ('lentsweletau_clinic', 'Lentsweletau clinic'), ('letlhakeng_clinic', 'Letlhakeng clinic'), ('oodi_clinic', 'Oodi clinic'), ('bokaa_clinic', 'Bokaa clinic'), ('metsimotlhabe_clinic', 'Metsimotlhabe clinic'), ('shoshong_clinic', 'Shoshong clinic'), ('sheleketla_clinic', 'Sheleketla clinic'), ('ramokgonami_clinic', 'Ramokgonami clinic'), ('lerala_clinic', 'Lerala clinic'), ('maunatlala_clinic', 'Maunatlala clinic'), ('sefophe_clinic', 'Sefophe clinic'), ('mmadinare_primary_hospital', 'Mmadinare Primary Hospital'), ('manga_clinic', 'Manga clinic'), ('mandunyane_clinic', 'Mandunyane clinic'), ('mathangwane_clinic', 'Mathangwane clinic'), ('tati_siding_clinic', 'Tati Siding clinic'), ('masunga_primary_hospital', 'Masunga Primary Hospital'), ('masunga_clinic', 'Masunga clinic'), ('mathangwane_clinic', 'Mathangwane clinic'), ('nata_clinic', 'Nata clinic'), ('OTHER', 'Other (specify)')], help_text='Hospital where subject is recruited', max_length=50, null=True)),
                ('enrollment_site_other', edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...')),
                ('is_eligible', models.BooleanField(default=False, editable=False)),
                ('ineligibility', models.TextField(editable=False, max_length=150, null=True, verbose_name='Reason not eligible')),
                ('is_consented', models.BooleanField(default=False, editable=False)),
                ('site', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name': 'Trainee+ Eligibility',
                'verbose_name_plural': 'Trainee+ Eligibility',
            },
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSubjectScreening',
            fields=[
                ('slug', models.CharField(db_index=True, default='', editable=False, help_text='a field used for quick search', max_length=250, null=True)),
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, db_index=True, editable=False, help_text='System auto field. UUID primary key.')),
                ('subject_identifier', models.CharField(max_length=50, verbose_name='Subject Identifier')),
                ('screening_identifier', models.CharField(db_index=True, max_length=36, verbose_name='Screening Identifier')),
                ('report_datetime', models.DateTimeField(default=edc_base.utils.get_utcnow, help_text='Date and time of the report', verbose_name='Report Date and Time')),
                ('enrollment_interest', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Does the patient want to be enrolledinto the study?')),
                ('disinterest_reason', models.CharField(blank=True, choices=[('dont_want_to_participate', "I don't want to be part of a study"), ('dont_think_I_have_condition', "I don't think I have the condition"), ('partner_doesnt_want_to_participate', "My partner doesn't want me to participate"), ('OTHER', 'Other (specify)')], max_length=50, null=True, verbose_name='If no, reason patient does not wish to enrollinto the study')),
                ('disinterest_reason_other', edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...')),
                ('nationality', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=3, verbose_name='Is the potential paticipant a Botswana Citizen?')),
                ('married_to_motswana', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=3, verbose_name='If no,Is participant married to a Motswana')),
                ('proof_of_marriage', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', help_text="( if 'NO' STOP patient cannot be enrolled )", max_length=3, verbose_name='If yes,Can the participate show proof of marriage')),
                ('age_in_years', models.IntegerField(help_text='(Years)', verbose_name='Paticipants age')),
                ('literate', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Is the participant literate')),
                ('literate_witness', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', max_length=3, verbose_name='If no,Does participant have a literate witness')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined')], max_length=6, verbose_name='Are you male or female?')),
                ('enrollment_site', models.CharField(choices=[('mmathethe_clinic', 'Mmathethe clinic'), ('molapowabojang_clinic', 'Molapowabojang clinic'), ('otse_clinic', 'Otse clinic'), ('mmankgodi_clinic', 'Mmankgodi clinic'), ('lentsweletau_clinic', 'Lentsweletau clinic'), ('letlhakeng_clinic', 'Letlhakeng clinic'), ('oodi_clinic', 'Oodi clinic'), ('bokaa_clinic', 'Bokaa clinic'), ('metsimotlhabe_clinic', 'Metsimotlhabe clinic'), ('shoshong_clinic', 'Shoshong clinic'), ('sheleketla_clinic', 'Sheleketla clinic'), ('ramokgonami_clinic', 'Ramokgonami clinic'), ('lerala_clinic', 'Lerala clinic'), ('maunatlala_clinic', 'Maunatlala clinic'), ('sefophe_clinic', 'Sefophe clinic'), ('mmadinare_primary_hospital', 'Mmadinare Primary Hospital'), ('manga_clinic', 'Manga clinic'), ('mandunyane_clinic', 'Mandunyane clinic'), ('mathangwane_clinic', 'Mathangwane clinic'), ('tati_siding_clinic', 'Tati Siding clinic'), ('masunga_primary_hospital', 'Masunga Primary Hospital'), ('masunga_clinic', 'Masunga clinic'), ('mathangwane_clinic', 'Mathangwane clinic'), ('nata_clinic', 'Nata clinic'), ('OTHER', 'Other (specify)')], help_text='Hospital where subject is recruited', max_length=50, null=True)),
                ('enrollment_site_other', edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...')),
                ('is_eligible', models.BooleanField(default=False, editable=False)),
                ('ineligibility', models.TextField(editable=False, max_length=150, null=True, verbose_name='Reason not eligible')),
                ('is_consented', models.BooleanField(default=False, editable=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(primary_key=True, serialize=False)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site')),
            ],
            options={
                'verbose_name': 'historical Trainee+ Eligibility',
                'verbose_name_plural': 'historical Trainee+ Eligibility',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
