# Generated by Django 4.2 on 2023-04-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsubjectscreening',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Trainee + Eligibility', 'verbose_name_plural': 'historical Trainee+ Eligibility'},
        ),
        migrations.AlterModelOptions(
            name='subjectscreening',
            options={'verbose_name': 'Trainee + Eligibility', 'verbose_name_plural': 'Trainee+ Eligibility'},
        ),
        migrations.RenameField(
            model_name='historicalsubjectscreening',
            old_name='nationality',
            new_name='citizen',
        ),
        migrations.RenameField(
            model_name='historicalsubjectscreening',
            old_name='married_to_motswana',
            new_name='legal_marriage',
        ),
        migrations.RenameField(
            model_name='historicalsubjectscreening',
            old_name='proof_of_marriage',
            new_name='marriage_certificate',
        ),
        migrations.RenameField(
            model_name='subjectscreening',
            old_name='nationality',
            new_name='citizen',
        ),
        migrations.RenameField(
            model_name='subjectscreening',
            old_name='married_to_motswana',
            new_name='legal_marriage',
        ),
        migrations.RenameField(
            model_name='subjectscreening',
            old_name='proof_of_marriage',
            new_name='marriage_certificate',
        ),
    ]
