# Generated by Django 4.2 on 2023-04-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_subject', '0002_alter_historicalsubjectscreening_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='disinterest_reason',
            field=models.CharField(blank=True, choices=[('dont_want_to_participate', "I don't want to be part of a study"), ('dont_think_I_have_condition', "I don't think I have the condition"), ('partner_doesnt_want_to_participate', "My partner doesn't want me to participate"), ('OTHER', 'Other (specify)')], max_length=50, null=True, verbose_name='If no, reason patient does not wish to enroll into the study'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='enrollment_interest',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Does the patient want to be enrolled into the study?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='disinterest_reason',
            field=models.CharField(blank=True, choices=[('dont_want_to_participate', "I don't want to be part of a study"), ('dont_think_I_have_condition', "I don't think I have the condition"), ('partner_doesnt_want_to_participate', "My partner doesn't want me to participate"), ('OTHER', 'Other (specify)')], max_length=50, null=True, verbose_name='If no, reason patient does not wish to enroll into the study'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='enrollment_interest',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Does the patient want to be enrolled into the study?'),
        ),
    ]
