# Generated by Django 3.1.14 on 2023-05-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_subject', '0003_historicalsubjectoffstudy_subjectoffstudy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloffschedule',
            name='consent_model',
        ),
        migrations.RemoveField(
            model_name='historicaloffschedule',
            name='consent_version',
        ),
        migrations.RemoveField(
            model_name='offschedule',
            name='consent_model',
        ),
        migrations.RemoveField(
            model_name='offschedule',
            name='consent_version',
        ),
    ]
