# Generated by Django 4.2 on 2023-04-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_subject', '0005_subjectlocator_historicalsubjectvisit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsubjectscreening',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Trainee + Eligibility', 'verbose_name_plural': 'historical Trainee + Eligibility'},
        ),
        migrations.AlterModelOptions(
            name='subjectscreening',
            options={'verbose_name': 'Trainee + Eligibility', 'verbose_name_plural': 'Trainee + Eligibility'},
        ),
        migrations.RemoveField(
            model_name='historicalsubjectscreening',
            name='age_in_years',
        ),
        migrations.RemoveField(
            model_name='subjectscreening',
            name='age_in_years',
        ),
        migrations.AddField(
            model_name='historicalsubjectscreening',
            name='guardian',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'No', participant may not be consented.", max_length=10, null=True, verbose_name='Is a guardian available?'),
        ),
        migrations.AddField(
            model_name='historicalsubjectscreening',
            name='is_minor',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text='If yes participant can not be consented', max_length=10, verbose_name='Is a minor(Under 18)'),
        ),
        migrations.AddField(
            model_name='historicalsubjectscreening',
            name='marriage_certificate_no',
            field=models.CharField(blank=True, help_text='e.g. 000/YYYY', max_length=9, null=True, verbose_name='What is the marriage certificate number?'),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='guardian',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'No', participant may not be consented.", max_length=10, null=True, verbose_name='Is a guardian available?'),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='is_minor',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text='If yes participant can not be consented', max_length=10, verbose_name='Is a minor(Under 18)'),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='marriage_certificate_no',
            field=models.CharField(blank=True, help_text='e.g. 000/YYYY', max_length=9, null=True, verbose_name='What is the marriage certificate number?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='legal_marriage',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], help_text="If 'No', participant not be consented", max_length=3, null=True, verbose_name='If no,Is participant married to a Motswana'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='marriage_certificate',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text="( if 'NO' STOP patient cannot be enrolled )", max_length=3, null=True, verbose_name='If yes,Can the participate show proof of marriage'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='legal_marriage',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], help_text="If 'No', participant not be consented", max_length=3, null=True, verbose_name='If no,Is participant married to a Motswana'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='marriage_certificate',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', help_text="( if 'NO' STOP patient cannot be enrolled )", max_length=3, null=True, verbose_name='If yes,Can the participate show proof of marriage'),
        ),
    ]
