# Generated by Django 4.2 on 2023-04-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_subject', '0006_alter_historicalsubjectscreening_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='guardian',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If No, participant may not be consented.', max_length=10, null=True, verbose_name='Is a guardian available?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='literate_witness',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=3, verbose_name='If no,Does participant have a literate witness'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='guardian',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If No, participant may not be consented.', max_length=10, null=True, verbose_name='Is a guardian available?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='literate_witness',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=3, verbose_name='If no,Does participant have a literate witness'),
        ),
    ]
