# Generated by Django 4.2 on 2023-04-26 10:24

import _socket
from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.model_validators.date
import edc_base.utils
import edc_protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('trainee_subject', '0007_alter_historicalsubjectscreening_guardian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalQuestionaire',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('form_as_json', models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True)),
                ('consent_model', models.CharField(editable=False, max_length=50, null=True)),
                ('consent_version', models.CharField(editable=False, max_length=10, null=True)),
                ('report_datetime', models.DateTimeField(default=edc_base.utils.get_utcnow, help_text="If reporting today, use today's date/time, otherwise use the date/time this information was reported.", validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Report Date')),
                ('working', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Are you currently working ?')),
                ('work_type', models.CharField(choices=[('formal_employment', 'Formal employment'), ('temporary_employment', 'Temporary Employment'), ('part_time_employment', 'Part-Time Employment'), ('self_employed', 'Self Employed'), ('retired', 'Retired'), ('OTHER', 'Other,specify')], max_length=100, verbose_name='In your main job what type of work do you do ?')),
                ('occupation', models.CharField(choices=[('Farmer (own land)', 'Farmer (own land)'), ('Farm work on employers land', 'Farm work on employers land'), ('Domestic worker', 'Domestic worker'), ('Work in bar/ hotel/ guest house/ entertainment venue', 'Work in bar/ hotel/ guest house/ entertainment venue'), ('Fishing', 'Fishing'), ('Mining', 'Mining'), ('Tourism/game parks', 'Tourism/game parks'), ('Working in shop / small business', 'Working in shop / small business'), ('Informal selling', 'Informal selling'), ('Commercial sex work', 'Commercial sex work'), ('Transport (trucker/ taxi driver)', 'Transport (trucker/ taxi driver)'), ('Factory worker', 'Factory worker'), ('Guard (security company)', 'Guard (security company)'), ('Police/ Soldier', 'Police/ Soldier'), ('Clerical and office work', 'Clerical and office work'), ('Government worker', 'Government worker'), ('Teacher', 'Teacher'), ('Health care worker', 'Health care worker'), ('Other professional', 'Other professional'), ("Don't want to answer", "Don't want to answer"), ('Other', 'Other')], max_length=100, verbose_name='Describe the work that you do or did in your most recent job')),
                ('salary', models.CharField(choices=[('No income', 'No income'), ('1 - 199 pula', '1 - 199 pula'), ('200 - 499 pula', '200 - 499 pula'), ('500 - 999 pula', '500 - 999 pula'), ('1000 - 4999 pula', '1000 - 4999 pula'), ('More than 10,000 pula', 'More than 10,000 pula')], max_length=150, verbose_name='In the past month, how much money did you earn from work you did or received in payment?')),
                ('site', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('subject_visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='trainee_subject.subjectvisit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
