# Generated by Django 4.2 on 2023-04-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_subject', '0008_educationalquestionaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalquestionaire',
            name='working',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('doesnt_work', 'Does not work')], max_length=11, verbose_name='Are you currently working ?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='guardian',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If No, participant may not be consented.', max_length=3, null=True, verbose_name='Is a guardian available?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='guardian',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If No, participant may not be consented.', max_length=3, null=True, verbose_name='Is a guardian available?'),
        ),
    ]
