# Generated by Django 4.2 on 2023-04-26 11:53

import _socket
from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.model_validators.date
import edc_base.utils
import edc_protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('trainee_subject', '0009_alter_educationalquestionaire_working_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEngagement',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('form_as_json', models.TextField(editable=False, help_text='System field to save form.as_json. form.as_json should be called in modeladmin.save_model', null=True)),
                ('consent_model', models.CharField(editable=False, max_length=50, null=True)),
                ('consent_version', models.CharField(editable=False, max_length=10, null=True)),
                ('report_datetime', models.DateTimeField(default=edc_base.utils.get_utcnow, help_text="If reporting today, use today's date/time, otherwise use the date/time this information was reported.", validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Report Date')),
                ('community_activity', models.CharField(choices=[('Very active', 'Very active'), ('Somewhat active', 'Somewhat active'), ('Not active at all', 'Not active at all'), ("Don't want to answer", "Don't want to answer")], max_length=50, verbose_name='How active are you in community activities such as burial society,Motshelo, Syndicate,PTA, VDC(Village Development Committee),Motshelo, Syndicate,PTA, VDC(Village Development Committee), Mophato and development of the community thatsurrounds you?')),
                ('voting_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not Applicable'), ('doesnt_want_to_answer', 'Does not want to answer')], max_length=21, verbose_name='Did you vote in the last local government election ?')),
                ('major_problems', models.CharField(choices=[(' HIV/AIDS', ' HIV/AIDS'), ('Schools', 'Schools'), ('Sewer', 'Sewer'), ('Unemployment', 'Unemployment'), ('Roads', 'Roads'), ('Water', 'Water'), ('Other, specify', 'Other, specify'), ('House', 'House'), ('Malaria', 'Malaria')], max_length=50, verbose_name='What are the major problems in this neighborhood?')),
                ('problem_solving', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('dont_know', 'Dont want to answer'), ('doesnt_want_to_answer', 'Does not want to answer')], max_length=50, verbose_name=' If there is a problem in this neighborhood, do the adults work together in solving it?')),
                ('site', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
                ('subject_visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='trainee_subject.subjectvisit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
