# Generated by Django 4.2 on 2023-04-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_subject', '0010_communityengagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityengagement',
            name='community_activity',
            field=models.CharField(choices=[('Very active', 'Very active'), ('Somewhat active', 'Somewhat active'), ('Not active at all', 'Not active at all'), ("Don't want to answer", "Don't want to answer")], max_length=50, verbose_name='How active are you in community activities such as burial society,Motshelo, Syndicate,PTA, VDC(Village Development Committee),Mophato and development of the community thatsurrounds you?'),
        ),
    ]
