# Generated by Django 4.2 on 2023-04-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_subject', '0012_alter_communityengagement_community_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityengagement',
            name='community_activity',
            field=models.CharField(choices=[('Very active', 'Very active'), ('Somewhat active', 'Somewhat active'), ('Not active at all', 'Not active at all'), ("Don't want to answer", "Don't want to answer")], help_text='Examples are Motshelo, Syndicate,PTA, VDC(Village Development Committee),Mophato and development of the community that surrounds you?', max_length=50, verbose_name='How active are you in community activities such as burial society,'),
        ),
        migrations.AlterField(
            model_name='communityengagement',
            name='problem_solving',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('dont_know', 'Dont Know'), ('doesnt_want_to_answer', 'Does not want to answer')], max_length=50, verbose_name='If there is a problem in this neighborhood,do the adults work together in solving it?'),
        ),
    ]
