# Generated by Django 4.2 on 2023-04-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_subject', '0015_historicalsubjectrequisition_subjectrequisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='is_minor',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If yes participant can not be consented', max_length=10, verbose_name='Is a minor(Under 18)'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='is_minor',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='If yes participant can not be consented', max_length=10, verbose_name='Is a minor(Under 18)'),
        ),
    ]
