# Generated by Django 4.2 on 2023-04-28 09:33

from django.db import migrations, models
import edc_base.model_fields.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_subject', '0016_alter_historicalsubjectscreening_is_minor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalquestionaire',
            name='work_type_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...'),
        ),
        migrations.AlterField(
            model_name='educationalquestionaire',
            name='work_type',
            field=models.CharField(choices=[('formal_employment', 'Formal employment'), ('temporary_employment', 'Temporary Employment'), ('part_time_employment', 'Part-Time Employment'), ('self_employed', 'Self Employed'), ('retired', 'Retired'), ('OTHER', 'Other,specify'), ('N/A', 'Not Applicable')], max_length=100, verbose_name='In your main job what type of work do you do ?'),
        ),
        migrations.AlterField(
            model_name='educationalquestionaire',
            name='working',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=11, verbose_name='Are you currently working ?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='may_call_work',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('does_not_work', 'Does not work')], max_length=25, verbose_name='Has the participant given permission to contacted <b>at work</b> by telephone or cell by study staff for follow-up purposes during the study?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='citizen',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Is the potential paticipant a Botswana Citizen?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='guardian',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], help_text='If No, participant may not be consented.', max_length=3, null=True, verbose_name='Is a guardian available?'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='may_call_work',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('does_not_work', 'Does not work')], max_length=25, verbose_name='Has the participant given permission to contacted <b>at work</b> by telephone or cell by study staff for follow-up purposes during the study?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='citizen',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Is the potential paticipant a Botswana Citizen?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='guardian',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], help_text='If No, participant may not be consented.', max_length=3, null=True, verbose_name='Is a guardian available?'),
        ),
    ]
