# Generated by Django 4.2 on 2023-04-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_subject', '0017_educationalquestionaire_work_type_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalquestionaire',
            name='work_type_other',
        ),
        migrations.AlterField(
            model_name='educationalquestionaire',
            name='occupation',
            field=models.CharField(choices=[('Farmer (own land)', 'Farmer (own land)'), ('Farm work on employers land', 'Farm work on employers land'), ('Domestic worker', 'Domestic worker'), ('Work in bar/ hotel/ guest house/ entertainment venue', 'Work in bar/ hotel/ guest house/ entertainment venue'), ('Fishing', 'Fishing'), ('Mining', 'Mining'), ('Tourism/game parks', 'Tourism/game parks'), ('Working in shop / small business', 'Working in shop / small business'), ('Informal selling', 'Informal selling'), ('Commercial sex work', 'Commercial sex work'), ('Transport (trucker/ taxi driver)', 'Transport (trucker/ taxi driver)'), ('Factory worker', 'Factory worker'), ('Guard (security company)', 'Guard (security company)'), ('Police/ Soldier', 'Police/ Soldier'), ('Clerical and office work', 'Clerical and office work'), ('Government worker', 'Government worker'), ('Teacher', 'Teacher'), ('Health care worker', 'Health care worker'), ('Other professional', 'Other professional'), ("Don't want to answer", "Don't want to answer"), ('Other', 'Other'), ('N/A', 'Not Applicable')], max_length=100, verbose_name='Describe the work that you do or did in your most recent job'),
        ),
        migrations.AlterField(
            model_name='educationalquestionaire',
            name='salary',
            field=models.CharField(choices=[('No income', 'No income'), ('1 - 199 pula', '1 - 199 pula'), ('200 - 499 pula', '200 - 499 pula'), ('500 - 999 pula', '500 - 999 pula'), ('1000 - 4999 pula', '1000 - 4999 pula'), ('More than 10,000 pula', 'More than 10,000 pula'), ('N/A', 'Not Applicable')], max_length=150, verbose_name='In the past month, how much money did you earn from work you did or received in payment?'),
        ),
        migrations.AlterField(
            model_name='educationalquestionaire',
            name='work_type',
            field=models.CharField(choices=[('formal_employment', 'Formal employment'), ('temporary_employment', 'Temporary Employment'), ('part_time_employment', 'Part-Time Employment'), ('self_employed', 'Self Employed'), ('self_employed_making_money_full_time', 'Self Employed Making Money Full Time'), ('self_employed_making_money_part_time', 'Self Employed Making Money Part Time'), ('OTHER', 'Other'), ('N/A', 'Not Applicable')], max_length=100, verbose_name='In your main job what type of work do you do ?'),
        ),
    ]
