# Generated by Django 4.2 on 2023-04-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee_subject', '0018_remove_educationalquestionaire_work_type_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityengagement',
            name='major_problems',
            field=models.CharField(choices=[(' HIV/AIDS', ' HIV/AIDS'), ('Schools', 'Schools'), ('Sewer', 'Sewer'), ('Unemployment', 'Unemployment'), ('Roads', 'Roads'), ('Water', 'Water'), ('House', 'House'), ('Malaria', 'Malaria'), ('dont_know', 'Dont Know')], max_length=50, verbose_name='What are the major problems in this neighborhood?'),
        ),
        migrations.AlterField(
            model_name='communityengagement',
            name='problem_solving',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('dont_know', 'Dont Know'), ('doesnt_want_to_answer', 'Does not want to answer'), ('N/A', 'Not Applicable')], max_length=50, verbose_name='If there is a problem in this neighborhood,do the adults work together in solving it?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='screening_identifier',
            field=models.CharField(db_index=True, editable=False, max_length=36, verbose_name='Screening Identifier'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='screening_identifier',
            field=models.CharField(editable=False, max_length=36, unique=True, verbose_name='Screening Identifier'),
        ),
    ]
